# ╭─────────────────────────Commonly Used ImplementationGuide Properties───────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. The most commonly   │
# │  used properties are included. For a list of all supported properties and their meanings,      │
# │  see: https://fshschool.org/docs/sushi/configuration/                                          │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.us.medicaid-plannet
canonical: http://hl7.org/fhir/us/medicaid-plannet
name: MedicaidPlanNet
title: "Medicaid Plan-Net Implementation Guide"
description: "FHIR Implementation Guide for Medicaid Plan-Net (provider directory) functionality based on Da Vinci Plan-Net and FAST NDH"
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2025+
releaseLabel: CI Build
pages:
  index.md:
    title: Home
  mita-overview.md:
    title: MITA Overview
  mita-implementation.md:
    title: MITA Implementation Guidance
  cms-interop-rule.md:
    title: CMS Interoperability Rule
  medicaid-plannet-resources.md:
    title: Medicaid Plan-Net Resources
  state-customization.md:
    title: State Customization Framework
  data-quality.md:
    title: Data Quality Framework
  security-privacy.md:
    title: Security and Privacy Considerations
  versioning-strategy.md:
    title: Versioning Strategy
  transition-strategy.md:
    title: Transition Strategy
  transition-principles.md:
    title: "Transition Strategy: Transition Principles"
  transition-patterns.md:
    title: "Transition Strategy: Transition Patterns"
  transition-planning.md:
    title: "Transition Strategy: Transition Planning"
  transition-assessment.md:
    title: "Transition Strategy: Transition Planning: Assessment"
  transition-strategy-development.md:
    title: "Transition Strategy: Transition Planning: Strategy Development"
  transition-implementation.md:
    title: "Transition Strategy: Transition Planning: Implementation Planning"
  transition-monitoring.md:
    title: "Transition Strategy: Transition Planning: Monitoring and Evaluation"
  transition-data.md:
    title: "Transition Strategy: Data Migration"
  transition-interface.md:
    title: "Transition Strategy: Interface Transition"
  transition-users.md:
    title: "Transition Strategy: User Transition"
  transition-operations.md:
    title: "Transition Strategy: Operational Transition"
  transition-technical.md:
    title: "Transition Strategy: Technical Transition"
  transition-examples.md:
    title: "Transition Strategy: Examples"
  transition-conclusions.md:
    title: "Transition Strategy: Conclusions"
  transition-references.md:
    title: "Transition Strategy: References"
  testing-framework.md:
    title: Testing Framework
  testing-principles.md:
    title: "Testing Framework: Testing Principles"
  conformance-testing.md:
    title: "Testing Framework: Conformance Testing"
  functional-testing.md:
    title: "Testing Framework: Functional Testing"
  performance-testing.md:
    title: "Testing Framework: Performance Testing"
  security-testing.md:
    title: "Testing Framework: Security Testing"
  test-automation.md:
    title: "Testing Framework: Test Automation"
  test-environments.md:
    title: "Testing Framework: Test Environments"
  test-implementation.md:
    title: "Testing Framework: Test Implementation"
  testing-references.md:
    title: "Testing Framework: References"
  examples.md:
    title: Examples
  downloads.md:
    title: Downloads

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Table of Contents: toc.html
  Background:
    MITA Overview: mita-overview.html
    MITA Implementation Guidance: mita-implementation.html
    CMS Interoperability Rule: cms-interop-rule.html
  FHIR Artifacts:
    Medicaid Plan-Net Resources: medicaid-plannet-resources.html
    Profiles: artifacts.html#structures-resource-profiles
    Extensions: artifacts.html#structures-extension-definitions
    Terminology: artifacts.html#terminology-value-sets
  Implementation Guidance:
    State Customization Framework: state-customization.html
    Data Quality Framework: data-quality.html
    Security and Privacy Considerations: security-privacy.html
    Versioning Strategy: versioning-strategy.html
    Transition Strategy: transition-strategy.html
    Testing Framework: testing-framework.html
  Examples: examples.html
  Downloads: downloads.html

# ╭───────────────────────────────────────────Dependencies────────────────────────────────────────╮
# │  To add a dependency on another implementation guide, add a new "dependsOn" entry.            │
# ╰──────────────────────────────────────────────────────────────────────────────────────────────╯
dependencies:
  hl7.fhir.us.davinci-pdex-plan-net:
    uri: http://hl7.org/fhir/us/davinci-pdex-plan-net/STU1.1
    version: 1.1.0
  hl7.fhir.us.ndh:
    uri: http://hl7.org/fhir/us/ndh/STU1
    version: 1.0.0
  hl7.fhir.us.core:
    uri: http://hl7.org/fhir/us/core/STU5.0.1
    version: 5.0.1

# ╭────────────────────────────────────────────Parameters───────────────────────────────────────────╮
# │  The parameters property represents IG.definition.parameter. Rather than a list of code/value   │
# │  pairs (as in the ImplementationGuide resource), the code is the YAML key. If a parameter      │
# │  allows repeating values, the value in the YAML should be a sequence/array. For a complete     │
# │  list of supported parameters, see the IG Parameters table in the SUSHI documentation.         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
parameters:
  path-resource:
    - input/resources
    - fsh-generated/resources
  path-pages:
    - input/pagecontent
    - input/intro-notes
  #path-expansion-params: expansion-parameters.json
  show-inherited-invariants: false
  usage-stats-opt-out: true
  excludexml: true
  excludejsn: false
  excludettl: true
  excludemap: true
  active-tables: false
  codesystem-snomed: http://snomed.info/sct/731000124108/version/20230901

# ╭────────────────────────────────────────────Resources────────────────────────────────────────────╮
# │  The resources property corresponds to IG.definition.resource. SUSHI can auto-generate          │
# │  resources based on FSH definitions and/or information in the FSH project. If a resource        │
# │  entry has a profile, it will be used as the logical URL (and optionally the canonical URL)     │
# │  for the resource. If a resource entry does not have a profile, it will be added to the         │
# │  resource list without any profile. If the resource entry has a profile that is defined in      │
# │  the FSH project, it will be used as the logical URL and the canonical URL for the resource.    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
# resources:
#   Patient/example:
#     name: Patient Example
#     description: An example Patient
#     exampleBoolean: true
